export const BACKEND_URL = 'https://backend.revilink.io'
export const API_URL = 'https://backend.revilink.io/api'
export const BUCKET_URL = 'https://revilink.s3.eu-central-1.amazonaws.com'
export const DOMAIN = 'https://revilink.io'
export const URL = 'https://revilink.io'
